#!/usr/bin/env bash
# Install nginx web server

TEXT="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sed -i "37i $TEXT" /etc/nginx/sites-available/default
service nginx stop
service nginx start
