#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx

echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://finalesoft.tech/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
