#!/usr/bin/env bash

#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
FLAG=1
while [ $FLAG = 1 ]; do
    trap "echo I am invincible!!!" SIGTERM
    echo "To infinity and beyond"
    sleep 2

done
