#!/usr/bin/env bash
# Write a Bash script that kills the process 7-highlander.
# Write a Bash script that displays a list of currently running processes.
PCS=$(pgrep -f 7-highlander)
for pid_ in $PCS; do
    kill -9 "$pid_"
done
