#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
CONTADOR=0
while [  $CONTADOR -lt 10 ]; do
    if [ $CONTADOR = 8 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    let CONTADOR=CONTADOR+1
done
